apiVersion: v1
kind: Pod
metadata:
  name: colocated-containers-demo
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    - name: redis
      image: redis