apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: httpd
      labels:
        tier: frontend
    spec:
      containers:
        - name: httpd-pod
          image: httpd:2.4-alpine