apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myweb
      type: front-end
  template:
    metadata:
      name: front-end
      labels:
        app: myweb
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx