# mychart/templates/configmap.yaml
{{- include "mychart.validators.portRange" .Values.port -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  port: {{ .Values.port }}